# Generated by Django 4.2.9 on 2025-07-31 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=50)),
                ('gerencia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Rols',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('roles', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rols',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.IntegerField(db_column='video_id', primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('person_id', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.DO_NOTHING, to='videos.person')),
                ('rol_id', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.DO_NOTHING, to='videos.rols')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
