# Generated by Django 4.2.9 on 2025-08-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_id',
            field=models.AutoField(db_column='video_id', primary_key=True, serialize=False),
        ),
    ]
