# Generated by Django 4.2.9 on 2025-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videos_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='location',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
