# Generated by Django 5.2.4 on 2025-08-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_videos_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='location',
            field=models.FileField(upload_to='video/'),
        ),
    ]
